//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyNetworkDomain
    {
        public int CNCId { get; set; }
        public string Domain { get; set; }
        public string NetworkTimeServer { get; set; }
        public int CompanyId { get; set; }
    }
}
