//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firewallinformation
    {
        public int FirewallId { get; set; }
        public string HostName { get; set; }
        public string DNSName { get; set; }
        public string SelectManufacturer { get; set; }
        public string Model { get; set; }
        public string OS { get; set; }
        public string OSVersion { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime InstallDate { get; set; }
        public System.DateTime WarrantyStarted { get; set; }
        public System.DateTime WarrantyExpires { get; set; }
        public string UploadFirewallConfiguration { get; set; }
        public string Notes { get; set; }
        public string SelectTag { get; set; }
        public int CompanyId { get; set; }
    }
}
