//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int InviteId { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsRegistered { get; set; }
    }
}
