//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteNetworkDomainstory
    {
        public string SiteDomain { get; set; }
        public int DomainStoryId { get; set; }
        public string NetworkId { get; set; }
        public string SubnetMask { get; set; }
        public string Gateway { get; set; }
        public string VLANNumber { get; set; }
        public string VLANName { get; set; }
        public string DNSServer { get; set; }
        public string DHCPServer { get; set; }
        public string DHCPIPRanges { get; set; }
    }
}
