//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpotEntities : DbContext
    {
        public SpotEntities()
            : base("name=SpotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<PasswordAttempt> PasswordAttempts { get; set; }
        public virtual DbSet<ValidateDomain> ValidateDomains { get; set; }
        public virtual DbSet<OrganizationDetail> OrganizationDetails { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<SiteNetworkDomainstory> SiteNetworkDomainstories { get; set; }
        public virtual DbSet<DevicePassword> DevicePasswords { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTag> UserTags { get; set; }
        public virtual DbSet<GeneratePassword> GeneratePasswords { get; set; }
        public virtual DbSet<GroupDetail> GroupDetails { get; set; }
        public virtual DbSet<ApplicationDetail> ApplicationDetails { get; set; }
        public virtual DbSet<CompanySite> CompanySites { get; set; }
        public virtual DbSet<Firewallinformation> Firewallinformations { get; set; }
        public virtual DbSet<ServerInfo> ServerInfoes { get; set; }
        public virtual DbSet<WorkStationInfo> WorkStationInfoes { get; set; }
        public virtual DbSet<SoftwareDetail> SoftwareDetails { get; set; }
        public virtual DbSet<SoftwarePackageDetail> SoftwarePackageDetails { get; set; }
        public virtual DbSet<CompanyNetworkDomain> CompanyNetworkDomains { get; set; }
        public virtual DbSet<RouterInfo> RouterInfoes { get; set; }
        public virtual DbSet<SwitchInfo> SwitchInfoes { get; set; }
        public virtual DbSet<NetworkInterface> NetworkInterfaces { get; set; }
        public virtual DbSet<DeviceforUser> DeviceforUsers { get; set; }
        public virtual DbSet<UsersGroup> UsersGroups { get; set; }
        public virtual DbSet<UserApplication> UserApplications { get; set; }
    }
}
