//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public string PrimaryPhone { get; set; }
        public string Extension { get; set; }
        public string AlternatePhone { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public bool IsPrimaryContact { get; set; }
        public string Notes { get; set; }
    }
}
