//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkStationInfo
    {
        public int WorkStationId { get; set; }
        public string HostName { get; set; }
        public string DNSName { get; set; }
        public string SelectManufacturer { get; set; }
        public string SelectModel { get; set; }
        public string SelectManufacturerPartNumber { get; set; }
        public string SelectOS { get; set; }
        public string SelectOSVersion { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime InstallDate { get; set; }
        public System.DateTime WarrantyStarted { get; set; }
        public System.DateTime WarrantyExpires { get; set; }
        public string SelectServerRoles { get; set; }
        public string Notes { get; set; }
        public string SelectTag { get; set; }
        public string SoftwareType { get; set; }
        public string SoftwareVersion { get; set; }
        public string LicenseKey { get; set; }
        public System.DateTime ExpiresOn { get; set; }
        public int CompanyId { get; set; }
    }
}
